"""project lifecycle state

Revision ID: 01b8582bbbf8
Revises: b3390474191e
Create Date: 2026-09-12 20:20:28.445524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b8582bbbf8'
down_revision: Union[str, None] = 'b3390474191e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default is required here even though it's autogenerated as absent -- adding a
    # NOT NULL column to a table that already has rows fails outright on Postgres without one
    # (and SQLite's ALTER TABLE ADD COLUMN has the same requirement). Dropped again right after
    # backfilling existing rows, since new rows already get "DISCOVERED" from the ORM-level
    # default (app.core.models.project.Project.state) -- the DB default only needs to exist
    # long enough to make this specific ADD COLUMN safe.
    op.add_column(
        'projects',
        sa.Column(
            'state',
            sa.Enum(
                'DISCOVERED', 'QUALIFIED', 'SURVEY_REQUIRED', 'SURVEYED', 'CONFIGURED', 'ESTIMATED',
                'BUDGETARY_QUOTE', 'FINAL_QUOTE', 'CONFIRMED', 'PROCUREMENT_READY', 'IN_PROGRESS',
                'HANDOVER', 'KNOWLEDGE_HARVEST', 'LIFECYCLE',
                name='project_state', native_enum=False, create_constraint=True,
            ),
            nullable=False,
            server_default='DISCOVERED',
        ),
    )
    # Plain op.alter_column(..., server_default=None) emits "ALTER TABLE ... ALTER COLUMN ...
    # DROP DEFAULT", which isn't valid SQLite syntax at all (SQLite has no ALTER COLUMN of any
    # kind). batch_alter_table is Alembic's standard cross-dialect answer: on Postgres it emits
    # the plain ALTER directly; on SQLite it transparently recreates the table with the desired
    # schema and copies the data across.
    with op.batch_alter_table('projects') as batch_op:
        batch_op.alter_column('state', server_default=None)


def downgrade() -> None:
    op.drop_column('projects', 'state')
