"""site quality flags (C10 healthy sites)

Revision ID: 1b02412312c5
Revises: 8c13f4750ea9
Create Date: 2026-09-12 22:59:29.888301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b02412312c5'
down_revision: Union[str, None] = '8c13f4750ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_quality_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('flag_type', sa.Enum('BAD_PAYMENT', 'REPEATED_SCOPE_ABUSE', 'MARGIN_LEAKAGE', 'HIGH_DISPUTE', 'EXCESSIVE_ADMIN_BURDEN', 'UNSAFE_PRACTICES', 'POOR_CAPACITY_FIT', name='site_quality_flag_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('flagged_by', sa.String(length=128), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_quality_flags')
    # ### end Alembic commands ###
