"""website branch theme

Revision ID: 3a7eba010c47
Revises: 3fbebed7d349
Create Date: 2026-09-16 17:34:58.748225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7eba010c47'
down_revision: Union[str, None] = '3fbebed7d349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'website_branches',
        sa.Column('theme', sa.String(length=32), nullable=False, server_default='modern-industrial'),
    )
    # ### end Alembic commands ###
    # batch_alter_table is Alembic's cross-dialect way to drop the now-unneeded server default --
    # plain op.alter_column(..., server_default=None) isn't valid SQLite syntax (see
    # 01b8582bbbf8_project_lifecycle_state.py for the same pattern).
    with op.batch_alter_table('website_branches') as batch_op:
        batch_op.alter_column('theme', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_branches', 'theme')
    # ### end Alembic commands ###
