"""website studio: branch, page revisioning, widget instances

Revision ID: 3f23a7a8bfd8
Revises: 1b02412312c5
Create Date: 2026-09-12 23:45:00.618701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f23a7a8bfd8'
down_revision: Union[str, None] = '1b02412312c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('forked_from_branch_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forked_from_branch_id'], ['website_branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('website_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['website_branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'slug', name='uq_website_page_branch_slug')
    )
    op.create_table('website_page_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('restored_from_revision_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['website_pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'revision_number', name='uq_website_page_revision_number')
    )
    op.create_table('widget_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_revision_id', sa.Uuid(), nullable=False),
    sa.Column('widget_type', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('visibility_rule', sa.Text(), nullable=True),
    sa.Column('content_source', sa.String(length=256), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['page_revision_id'], ['website_page_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widget_instances')
    op.drop_table('website_page_revisions')
    op.drop_table('website_pages')
    op.drop_table('website_branches')
    # ### end Alembic commands ###
