"""supplier and supplier quote

Revision ID: 47bc9f3c25b7
Revises: af26432a238e
Create Date: 2026-09-12 21:06:21.447233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bc9f3c25b7'
down_revision: Union[str, None] = 'af26432a238e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('material_description', sa.String(length=255), nullable=False),
    sa.Column('quoted_price', sa.Float(), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('lock_days', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('actual_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('actual_procurement_price', sa.Float(), nullable=True),
    sa.Column('moq', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_quotes')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
