"""quote revisioning with line items

Revision ID: af26432a238e
Revises: 09474f7c22f6
Create Date: 2026-09-12 20:51:34.400834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af26432a238e'
down_revision: Union[str, None] = '09474f7c22f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('true_cost', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('gm_percent', sa.Float(), nullable=False),
    sa.Column('gate_status', sa.Enum('PASS', 'OVERRIDE_REQUIRED', 'BLOCKED', name='gate_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('gate_note', sa.String(length=256), nullable=False),
    sa.Column('restored_from_revision_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id', 'revision_number', name='uq_quote_revision_number')
    )
    op.create_table('quote_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_revision_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['quote_revision_id'], ['quote_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_lines')
    op.drop_table('quote_revisions')
    op.drop_table('quotes')
    # ### end Alembic commands ###
