"""survey and site knowledge observations

Revision ID: b90c9fef9a65
Revises: 47bc9f3c25b7
Create Date: 2026-09-12 21:09:29.334705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90c9fef9a65'
down_revision: Union[str, None] = '47bc9f3c25b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=True),
    sa.Column('knowledge_type', sa.String(length=64), nullable=False),
    sa.Column('location_description', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('original_assumption', sa.Text(), nullable=True),
    sa.Column('observed_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('observed_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('applicability', sa.Text(), nullable=False),
    sa.Column('evidence_description', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_observations')
    op.drop_table('surveys')
    # ### end Alembic commands ###
