"""website branch font pair

Revision ID: bccbd4d65bb6
Revises: 3a7eba010c47
Create Date: 2026-09-17 12:48:24.170573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccbd4d65bb6'
down_revision: Union[str, None] = '3a7eba010c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'website_branches',
        sa.Column('font_pair', sa.String(length=32), nullable=False, server_default='classic'),
    )
    # ### end Alembic commands ###
    # batch_alter_table is Alembic's cross-dialect way to drop the now-unneeded server default --
    # see 3a7eba010c47_website_branch_theme.py for the same pattern and why it's needed for
    # SQLite compatibility.
    with op.batch_alter_table('website_branches') as batch_op:
        batch_op.alter_column('font_pair', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_branches', 'font_pair')
    # ### end Alembic commands ###
