"""website inquiry archive

Revision ID: db3aad56cab7
Revises: e390047b824d
Create Date: 2026-09-18 08:04:12.316550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3aad56cab7'
down_revision: Union[str, None] = 'e390047b824d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_inquiries', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_inquiries', 'archived_at')
    # ### end Alembic commands ###
