"""user login lockout

Revision ID: e390047b824d
Revises: bccbd4d65bb6
Create Date: 2026-09-18 07:38:54.025033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e390047b824d'
down_revision: Union[str, None] = 'bccbd4d65bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # batch_alter_table is Alembic's cross-dialect way to drop the now-unneeded server default --
    # see 3a7eba010c47_website_branch_theme.py for the same pattern and why it's needed for
    # SQLite compatibility.
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('failed_login_attempts', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
